#!/usr/bin/env python3
"""
Migrate Missing Chunks Script

Loads missing_chunk_ids.json (generated by scan_missing_chunks.py) and migrates
those chunks from Weaviate to Qdrant with lean payloads (only doc_id, data_source_id).

Usage:
    python migrate_missing_chunks.py
"""

import os
import sys
import json
import asyncio
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Tuple
from dotenv import load_dotenv
from tqdm import tqdm

import weaviate
from weaviate.classes.query import Filter
from qdrant_client import AsyncQdrantClient
from qdrant_client.models import PointStruct

# Configuration
ENV_FILE = Path(__file__).parent / ".env"
INPUT_FILE = Path(__file__).parent / "missing_chunk_ids.json"
CHECKPOINT_FILE = Path(__file__).parent / "migration_checkpoint.json"
LOG_FILE = Path(__file__).parent / "migrate_missing_chunks.log"

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.FileHandler(LOG_FILE), logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


class MissingChunkMigrator:
    """Migrates missing chunks from Weaviate to Qdrant."""

    def __init__(self):
        """Initialize migrator and load configuration."""
        self.load_environment()
        self.checkpoint = self.load_checkpoint()

    def load_environment(self):
        """Load configuration from .env file."""
        if not ENV_FILE.exists():
            raise FileNotFoundError(f"Environment file not found: {ENV_FILE}")

        load_dotenv(ENV_FILE)

        # Weaviate config
        self.weaviate_url = os.getenv("WEAVIATE_URL")
        self.weaviate_api_key = os.getenv("WEAVIATE_API_KEY")
        self.weaviate_collection = os.getenv("WEAVIATE_COLLECTION", "Text_tables")

        # Qdrant config
        self.qdrant_url = os.getenv("QDRANT_URL")
        self.qdrant_api_key = os.getenv("QDRANT_API_KEY")
        self.qdrant_collection = os.getenv("QDRANT_COLLECTION", "chunks")

        # Validate required vars
        required = [
            ("WEAVIATE_URL", self.weaviate_url),
            ("WEAVIATE_API_KEY", self.weaviate_api_key),
            ("QDRANT_URL", self.qdrant_url),
            ("QDRANT_API_KEY", self.qdrant_api_key),
        ]

        missing = [name for name, value in required if not value]
        if missing:
            raise ValueError(
                f"Missing required environment variables: {', '.join(missing)}"
            )

        logger.info("Environment configuration loaded successfully")
        logger.info(f"Weaviate: {self.weaviate_url} / {self.weaviate_collection}")
        logger.info(f"Qdrant: {self.qdrant_url} / {self.qdrant_collection}")

    def load_missing_ids(self) -> Dict[str, Any]:
        """Load missing chunk_ids from JSON file."""
        if not INPUT_FILE.exists():
            raise FileNotFoundError(
                f"Input file not found: {INPUT_FILE}\n"
                "Please run scan_missing_chunks.py first."
            )

        with open(INPUT_FILE) as f:
            data = json.load(f)

        logger.info(f"Loaded {data['total_missing']:,} missing chunk_ids from scan")
        logger.info(f"Scan timestamp: {data['scan_timestamp']}")

        return data

    def load_checkpoint(self) -> Dict:
        """Load checkpoint if exists, otherwise return empty checkpoint."""
        if CHECKPOINT_FILE.exists():
            try:
                with open(CHECKPOINT_FILE) as f:
                    checkpoint = json.load(f)
                logger.info(
                    f"Loaded checkpoint: {checkpoint['migrated_count']:,} chunks already migrated"
                )
                return checkpoint
            except Exception as e:
                logger.warning(f"Failed to load checkpoint: {e}")
                return self._init_checkpoint()
        return self._init_checkpoint()

    def _init_checkpoint(self) -> Dict:
        """Initialize new checkpoint."""
        return {
            "source_file": str(INPUT_FILE),
            "total_to_migrate": 0,
            "migrated_count": 0,
            "last_batch_index": 0,
            "migrated_chunk_ids": [],
            "failed_chunk_ids": [],
            "errors": [],
            "last_update": datetime.utcnow().isoformat(),
        }

    def save_checkpoint(self):
        """Save checkpoint to file."""
        try:
            self.checkpoint["last_update"] = datetime.utcnow().isoformat()
            with open(CHECKPOINT_FILE, "w") as f:
                json.dump(self.checkpoint, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save checkpoint: {e}")

    async def fetch_weaviate_chunks_by_ids(
        self, chunk_ids: List[str], weaviate_client
    ) -> List[Dict[str, Any]]:
        """Fetch chunks from Weaviate by chunk_id list.

        Args:
            chunk_ids: List of chunk_ids to fetch
            weaviate_client: Connected Weaviate client

        Returns:
            List of chunk dicts with chunk_id, doc_id, data_source_id, vector
        """
        chunks = []
        collection = weaviate_client.collections.get(self.weaviate_collection)

        # Weaviate doesn't support IN queries directly, so we fetch with filter
        # We'll use offset pagination to fetch all chunks
        # For efficiency, we fetch all with the chunk_id field and filter locally

        # Alternative: fetch in smaller sub-batches if the list is very large
        # For now, we'll fetch by iterating through chunk_ids
        # This is not optimal but Weaviate v4 client has limited batch get support

        # Better approach: Use whereFilter with ContainsAny if supported
        # For robustness, we'll fetch one by one with batching

        for i in range(0, len(chunk_ids), 100):
            batch_ids = chunk_ids[i : i + 100]

            for chunk_id in batch_ids:
                try:
                    response = collection.query.fetch_objects(
                        filters=Filter.by_property("chunk_id").equal(chunk_id),
                        limit=1,
                        include_vector=True,
                        return_properties=["chunk_id", "doc_id", "data_source_id"],
                    )

                    if response.objects:
                        obj = response.objects[0]

                        # Extract vector (handle named vectors)
                        vector = obj.vector
                        if isinstance(vector, dict) and "page_content_vector" in vector:
                            vector = vector["page_content_vector"]

                        chunks.append(
                            {
                                "chunk_id": obj.properties.get("chunk_id"),
                                "doc_id": obj.properties.get("doc_id"),
                                "data_source_id": obj.properties.get("data_source_id"),
                                "vector": vector,
                            }
                        )

                except Exception as e:
                    logger.warning(f"Failed to fetch chunk {chunk_id}: {e}")
                    continue

        return chunks

    async def fetch_and_migrate_batch(
        self, chunk_ids: List[str], weaviate_client, qdrant_client
    ) -> Tuple[int, List[str]]:
        """Fetch chunks from Weaviate and upsert to Qdrant.

        Args:
            chunk_ids: List of chunk_ids to migrate
            weaviate_client: Connected Weaviate client
            qdrant_client: Connected Qdrant client

        Returns:
            Tuple of (success_count, failed_chunk_ids)
        """
        failed_ids = []

        # Retry logic with exponential backoff
        for attempt in range(5):
            try:
                # 1. Fetch from Weaviate
                weaviate_chunks = await self.fetch_weaviate_chunks_by_ids(
                    chunk_ids, weaviate_client
                )

                if not weaviate_chunks:
                    logger.warning(f"No chunks found in Weaviate for batch")
                    return 0, chunk_ids

                # 2. Build Qdrant points (lean payload)
                points = []
                fetched_ids = set()

                for chunk in weaviate_chunks:
                    if not chunk.get("chunk_id") or not chunk.get("vector"):
                        continue

                    fetched_ids.add(chunk["chunk_id"])

                    point = PointStruct(
                        id=chunk["chunk_id"],
                        vector=chunk["vector"],
                        payload={
                            "doc_id": chunk.get("doc_id", ""),
                            "data_source_id": chunk.get("data_source_id", ""),
                        },
                    )
                    points.append(point)

                # Track which chunk_ids we couldn't fetch
                for chunk_id in chunk_ids:
                    if chunk_id not in fetched_ids:
                        failed_ids.append(chunk_id)

                if not points:
                    return 0, chunk_ids

                # 3. Upsert to Qdrant
                await qdrant_client.upsert(
                    collection_name=self.qdrant_collection, points=points, wait=True
                )

                return len(points), failed_ids

            except Exception as e:
                if attempt == 4:
                    logger.error(f"Failed to migrate batch after 5 attempts: {e}")
                    return 0, chunk_ids

                wait_time = 2**attempt
                logger.warning(
                    f"Attempt {attempt + 1}/5 failed: {e}. Retrying in {wait_time}s..."
                )
                await asyncio.sleep(wait_time)

        return 0, chunk_ids

    async def migrate(self):
        """Main migration loop."""
        logger.info("=" * 80)
        logger.info("Starting Missing Chunk Migration")
        logger.info("=" * 80)

        try:
            # Load missing chunk_ids
            missing_data = self.load_missing_ids()
            all_missing_ids = missing_data["missing_chunk_ids"]

            # Filter out already migrated
            already_migrated = set(self.checkpoint.get("migrated_chunk_ids", []))
            to_migrate = [cid for cid in all_missing_ids if cid not in already_migrated]

            logger.info(f"Total missing from scan: {len(all_missing_ids):,}")
            logger.info(f"Already migrated: {len(already_migrated):,}")
            logger.info(f"Remaining to migrate: {len(to_migrate):,}")

            if not to_migrate:
                logger.info("All chunks already migrated. Nothing to do.")
                return

            # Update checkpoint
            if self.checkpoint["total_to_migrate"] == 0:
                self.checkpoint["total_to_migrate"] = len(all_missing_ids)
                self.checkpoint["scan_timestamp"] = missing_data["scan_timestamp"]

            # Connect to databases
            logger.info("Connecting to Weaviate and Qdrant...")
            weaviate_client = weaviate.connect_to_weaviate_cloud(
                cluster_url=self.weaviate_url,
                auth_credentials=weaviate.classes.init.Auth.api_key(
                    self.weaviate_api_key
                ),
                skip_init_checks=False,
            )

            qdrant_client = AsyncQdrantClient(
                url=self.qdrant_url,
                api_key=self.qdrant_api_key,
            )

            # Batch migrate
            batch_size = 1000
            total_batches = (len(to_migrate) + batch_size - 1) // batch_size

            logger.info(f"Starting migration in batches of {batch_size}...")

            with tqdm(
                total=len(to_migrate), desc="Migrating chunks", unit=" chunks"
            ) as pbar:
                for i in range(0, len(to_migrate), batch_size):
                    batch = to_migrate[i : i + batch_size]
                    batch_num = i // batch_size + 1

                    logger.info(
                        f"Batch {batch_num}/{total_batches}: Processing {len(batch)} chunks..."
                    )

                    success_count, failed = await self.fetch_and_migrate_batch(
                        batch, weaviate_client, qdrant_client
                    )

                    # Update checkpoint
                    self.checkpoint["migrated_chunk_ids"].extend(batch)
                    self.checkpoint["failed_chunk_ids"].extend(failed)
                    self.checkpoint["migrated_count"] += success_count
                    self.checkpoint["last_batch_index"] = batch_num

                    if failed:
                        for chunk_id in failed:
                            self.checkpoint["errors"].append(
                                {
                                    "chunk_id": chunk_id,
                                    "error": "Failed to fetch or migrate",
                                    "timestamp": datetime.utcnow().isoformat(),
                                }
                            )

                    # Save checkpoint every 10 batches
                    if batch_num % 10 == 0:
                        self.save_checkpoint()
                        logger.info(
                            f"[Checkpoint saved: {self.checkpoint['migrated_count']:,} chunks migrated]"
                        )

                    pbar.update(len(batch))

            # Final checkpoint save
            self.save_checkpoint()

            # Cleanup
            weaviate_client.close()
            await qdrant_client.close()

            logger.info("=" * 80)
            logger.info("Migration Complete!")
            logger.info(f"  Total to migrate: {len(all_missing_ids):,}")
            logger.info(
                f"  Successfully migrated: {self.checkpoint['migrated_count']:,}"
            )
            logger.info(f"  Failed: {len(self.checkpoint['failed_chunk_ids']):,}")
            if self.checkpoint["failed_chunk_ids"]:
                logger.info(f"  See {CHECKPOINT_FILE} for failed chunk details")
            logger.info("=" * 80)

        except Exception as e:
            logger.error(f"Fatal error during migration: {e}", exc_info=True)
            # Save checkpoint on error
            self.save_checkpoint()
            raise


async def main():
    """Entry point."""
    try:
        migrator = MissingChunkMigrator()
        await migrator.migrate()
    except KeyboardInterrupt:
        logger.info("\nMigration interrupted by user. Progress saved to checkpoint.")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Migration failed: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
